### ISSUE TITLE
French address extraction 

### ISSUE THREAD

**Issue by Elfilali-Taoufiq** [onethinglab/address_extraction#2]
hello, 

thanks for this great work, it is  so helpful.
I want to extract adresses from  french text, is there some suggestion to use this work or some other Datasets for french?

thank you

**Comment by bagrii** [comment]
Hi,

No, this dataset will not work for the french addresses as they have different format (I guess).

I think you can create you own dataset, by scraping websites like yelp or tripadvisor. The idea is that, on those websites there is an address of a place in a HTML element and the website of a place. So, you can automatically extract the address of a place from yelp/tripadvisor and crawl the website URL of a place and try to find this address there, if it's there, then mark the text tokens using IOB tags. Repeat this for all places in France and you will compile huge dataset of addresses :smile:
